title = "Jinwoo Park Blog"

[author]
name = "Jinwoo Park"
image = "img/profile.jpeg"
headline = "Rust + Linux + Embedded + Electronics"
bio = "Working as a Rust Backend Engineer and previously worked as an Embedded Systems Engineer."
links = [
  { github = "https://github.com/pmnxis" }
]