# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

mainSections = ["docs", "samples"]
# robots = ""

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  # layout = "custom" # valid options: page, profile, custom
  showRecent = true
  showRecentItems = 5
  # showMoreLink = false
  # showMoreLinkDest = "/docs"
 
[article]
  # showDate = false
  # showViews = true
  # showLikes = true
  # showDateUpdated = false
  showAuthor = true
  # showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  # editURL = "https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true 
  showWordCount = false
  showSummary = true
  # sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email"]

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  groupByYear = false

[sitemap]
  # excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
